apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent
  namespace: monitoring
  labels:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  source:
    repoURL: 'https://github.com/leelax22/argotest.git'
    path: loki/grafana-agent-event
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true